# Generated by Django 3.2.8 on 2021-12-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Chapter',
        ),
    ]
