# Generated by Django 3.2.8 on 2021-12-18 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_rename_file_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
