# Generated by Django 3.2.8 on 2021-12-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_alter_chapter_chap'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=250),
        ),
    ]
