# Generated by Django 3.2.8 on 2021-12-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
    ]
