# Generated by Django 4.0.2 on 2022-03-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_alter_series_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.ImageField(upload_to='media/covers'),
        ),
    ]
